#!/bin/bash
. ./uni-global_var

if [ -r $cookie_path ];then
	cookie=$(grep PHPSESSID $cookie_path)
fi

if [ $# -eq 0 ];then
	echo "$0 : no arguments" 1>&2
	exit 1
fi

while [ ! $# -eq 0 ] ; do
	choice=$1
	shift
	case $choice in
	'-d')
		if [ ! -d "$1" ];then
			echo "$0 Directory \"$1\" does not exist!" 1>&2
			exit 1
		fi
		#path=$(realpath .)
		path=$1
		shift
		;;
	'-f')
		if [ ! -r "$1" ];then
			echo "$0 Cannot read file!" 1>&2
			exit 1
		fi
		j=0
		for i in $(cut -f 1 -d ' ' $1); do
			args[$j]=$i
			j=$j+1
		done
		j=0
		for i in $(cut -s -f 2 -d ' ' $1); do
			names[$j]=$i
			j=$j+1
		done
		shift
		#echo ${#args[*]}
		#echo ${args[*]}
		#echo ${#names[*]}
		#echo ${names[*]}
		#exit
		;;
	'-e')
		args=$@
		shift $#
		;;
	'--help')
		echo "Not implemented"
		exit 0
		;;
	esac
done

if [ -p /dev/stdin ]; then
	args=$(cat)
elif [ ! -t 0 ] ; then
	while read -r line ; do
		args="$args "$line
	done
fi

for((i=0; i<${#args[*]};i++)); do
ID="${args[$i]}"
curl -I -s "https://eclass.uniwa.gr/modules/document/index.php?course=$ID&download=/" -H  "$accept" -H "$accept_language" --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H "Referer: https://eclass.uniwa.gr/modules/document/?course=$ID" -H "Cookie: $cookie" -H 'Upgrade-Insecure-Requests: 1' -H 'If-Modified-Since: Mon, 04 Nov 2019 20:27:50 GMT' -H 'If-None-Match: 481b6876ecdb4cf52837c28074187544' -H 'TE: Trailers' > /tmp/qaztmp
filename=$(cat /tmp/qaztmp | grep filename= | sed -r 's/.*filename=[[:punct:]]?([^"]*)[[:punct:]]?/\1/')
extension=$(cat /tmp/qaztmp | grep content-type: | sed -r 's/.*application\/([[:alpha:]]*).*/\1/')

if [ $i -le ${#names[*]} ]  && [ "${names[$i]}" != "" ]; then
	filename="${names[$i]}"".$extension"
else
	filename=$(echo $filename | sed "s/[[:space:]]/_/g")
	filename=$(echo $filename | sed "s/_$//g")
fi

#echo "f="$filename
#echo "p="$path

curl "https://eclass.uniwa.gr/modules/document/index.php?course=$ID&download=/" -H  "$accept" -H "$accept_language" --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H "Referer: https://eclass.uniwa.gr/modules/document/?course=$ID" -H "Cookie: $cookie" -H 'Upgrade-Insecure-Requests: 1' -H 'If-Modified-Since: Mon, 04 Nov 2019 20:27:50 GMT' -H 'If-None-Match: 481b6876ecdb4cf52837c28074187544' -H 'TE: Trailers' -o "$path/$filename"

done

exit 0
